name: Run Database Migration

on:
  push:
    branches: [ main ]

jobs:
  laravel-migration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo, pdo_pgsql, pgsql
        tools: composer:v2

    # Buat file .env minimalis agar Artisan aman saat dinyalakan
    - name: Create Env File
      run: |
        echo "APP_ENV=production" > .env
        echo "APP_KEY=base64:7nBv6RWhL8T76j9KmPnBv6RWhL8T76j9KmPzBcDeFgHi=" >> .env

    # Tambahkan bendera ignore-platform-reqs agar tidak rewel urusan versi extension
    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

    - name: Run Migration to Supabase
      env:
        DB_CONNECTION: pgsql
        # Trik Pamungkas: Gabungkan kredensial dan opsi SSL langsung ke dalam satu URL tunggal
        DB_URL: postgresql://postgres:jangandihackya@db.adfrmljnbgdcajwpocco.supabase.co:5432/postgres?sslmode=require
      run: php artisan migrate --force

      